"""empty message

Revision ID: fc75492ff226
Revises: 
Create Date: 2019-09-01 21:59:20.389223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc75492ff226'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_center',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('realname', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('usertype', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usertype'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('timesheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('totaltime', sa.String(), nullable=True),
    sa.Column('inlocation', sa.String(length=255), nullable=True),
    sa.Column('outlocation', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('clockedin', sa.Boolean(), nullable=True),
    sa.Column('costcenter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['costcenter'], ['cost_center.id'], ),
    sa.ForeignKeyConstraint(['employee'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheet_date'), 'timesheet', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheet_date'), table_name='timesheet')
    op.drop_table('timesheet')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('cost_center')
    # ### end Alembic commands ###
